Add checks and clean-up to remote starts.

diff --git a/bin/gaspi_run b/bin/gaspi_run
--- a/bin/gaspi_run
+++ b/bin/gaspi_run
@@ -29,6 +29,8 @@ HN=`/bin/hostname`
 TMP_PATTERN=".gpi2.XXXXXXXX"
 TMP_MFILE=$(TMPDIR=. mktemp ${TMP_PATTERN})
 UNIQ_MFILE=$(TMPDIR=. mktemp ${TMP_PATTERN})
+RUN_PATTERN=".gaspi_run.XXXXXXXX"
+RUN_FILE=$(TMPDIR=. mktemp ${RUN_PATTERN})
 ORIG_MFILE=""
 NNODES=0
 DEBUG=0
@@ -52,6 +54,7 @@ remove_temp_file()
 {    
     rm -f $TMP_MFILE
     rm -f $UNIQ_MFILE
+    rm -f $RUN_FILE
 }
 
 clean_exit()
@@ -218,10 +221,6 @@ fi
 
 validate_machinefile $MFILE
 
-#master binary is the same
-if [ "$MASTER_PRG" = "" ]; then
-    MASTER_PRG=$PRG
-fi
 
 hlist=`cat $MFILE`
 t=0
@@ -235,6 +234,11 @@ TMP_KPRG=`readlink -f $KPRG`
 
 PRG=$TMP_PRG
 KPRG=$TMP_KPRG
+
+#master binary is the same
+if [ "$MASTER_PRG" = "" ]; then
+    MASTER_PRG=$PRG
+fi
 
 #who's master
 master_node=`head -n 1 $MFILE`
@@ -270,12 +274,12 @@ do
     fi
 
     if [ $SET_NUMA -eq 1 ]; then    
-	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE;export GASPI_SET_NUMA_SOCKET=1; $PRG > /dev/null 2>&1 &'"
+	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE;export GASPI_SET_NUMA_SOCKET=1; if [ -x $PRG ]; then $PRG; else echo '$i': '$PRG' not found;exit 1;fi 2> /dev/null &'"
     else
-	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE; $PRG > /dev/null 2>&1 &'"
+	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE; if [ -x $PRG ]; then $PRG;else echo '$i': '$PRG' not found;exit 1;fi 2> /dev/null &'"
     fi
 
-    ssh $i $cmd &
+    ssh $i $cmd  >> $RUN_FILE &
 
     previous="$i"
 
@@ -287,20 +291,43 @@ if [ -O /tmp/.last_gaspi_prg ]; then
     chmod a+rw /tmp/.last_gaspi_prg &> /dev/null
 fi
 
+#check all started well
+sleep 1
+if [ `wc -l $RUN_FILE |gawk '{print $1}'` != "0" ]; then 
+    echo "Error: Failed to start $PRG on remote nodes"
+    echo
+    cat $RUN_FILE
+    echo
+    clean_exit
+    exit 1
+fi
+
 #start master
+t1=$(date +%s)
+tdiff=$(( $t1 - $t0 ))
+echo ssh-startup time: $tdiff sec
 
 if [ "$master_node" != "$HN" ]; then
     #prepare differently for remote node
-    chmod a+r $MFILE
+    chmod a+r $MFILE &> /dev/null
     TMP_FILE=`readlink -f $MFILE`
     MFILE=$TMP_FILE
-    
+    scp $MFILE ${master_node}:${MFILE} &> /dev/null
+    if [ $? != 0 ]; then
+	echo "Warning: Failed to copy machinefile to remote host. Program might not start correctly."
+    fi
+
     if [ $SET_NUMA -eq 1 ]; then    
- 	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=0;export GASPI_TYP=GASPI_MASTER;export GASPI_MFILE=$MFILE;export GASPI_SET_NUMA_SOCKET=1; $PRG'"
+ 	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=0;export GASPI_TYP=GASPI_MASTER;export GASPI_MFILE=$MFILE;export GASPI_SET_NUMA_SOCKET=1; $MASTER_PRG'"
     else
- 	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=0;export GASPI_TYP=GASPI_MASTER;export GASPI_MFILE=$MFILE; $PRG'"
+ 	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=0;export GASPI_TYP=GASPI_MASTER;export GASPI_MFILE=$MFILE; $MASTER_PRG'"
      fi
-     ssh $master_node $cmd 
+    ssh $master_node $cmd 
+    if [ $? != 0 ]; then
+	echo "Error: Failed to start $MASTER_PRG on $master_node"
+	clean_exit
+	exit 1
+    fi
 else
     export GASPI_MASTER=$HN;
     
@@ -311,9 +338,6 @@ else
     export GASPI_TYP=GASPI_MASTER;
     export GASPI_MFILE=$MFILE;
     
-    t1=$(date +%s)
-    tdiff=$(( $t1 - $t0 ))
-    echo ssh-startup time: $tdiff sec
 
     if [ $DEBUG != 0 ]; then
 	gdb --args $MASTER_PRG
