gaspi_run: move finding and setting NUMA option to own function.

diff --git a/bin/gaspi_run b/bin/gaspi_run
--- a/bin/gaspi_run
+++ b/bin/gaspi_run
@@ -80,6 +80,23 @@ print_error_exit_failure()
     exit 1
 }
 
+find_set_NUMA_config()
+{
+    which numactl &> /dev/null
+    if [ $? = 0 ]; then
+        MAX_NUMA_NODES=$(numactl --hardware|grep available|gawk '{print $2}')
+	SET_NUMA=1
+    else
+	which lscpu &> /dev/null
+	if [ $? = 0 ]; then
+            MAX_NUMA_NODES=$(lscpu|grep "NUMA node(s)"|gawk '{print $3}')
+	else
+            echo "Warning: unable to detect NUMA configuration. Option not used."
+	    SET_NUMA=0
+	fi
+    fi
+}
+
 validate_machinefile()
 {
     if [ ! -s $MFILE ]; then
@@ -171,7 +188,7 @@ while [ -n "$1" ]; do
             fi
             ;;
         -N | --NUMA)
-            SET_NUMA=1
+	    find_set_NUMA_config
             ;;
         -d | --debug)
             DEBUG=1
@@ -234,13 +251,6 @@ fi
 trap kill_procs TERM INT QUIT
 
 #sanity check and settings
-if [ $SET_NUMA -eq 1 ]; then
-    MAX_NUMA_NODES=1
-    which numactl > /dev/null
-    if [ $? = 0 ]; then
-        MAX_NUMA_NODES=$(numactl --hardware|grep available|gawk '{print $2}')
-    fi
-fi
 
 #use all hosts in machines file
 if [ $NNODES -eq 0 ]; then
