gaspi_run: make next cmd contruction easier to read

diff --git a/bin/gaspi_run b/bin/gaspi_run
--- a/bin/gaspi_run
+++ b/bin/gaspi_run
@@ -267,11 +267,15 @@ do
 	j=0
     fi
 
+    cmd="/bin/sh -c"
+    cmd="$cmd 'export GASPI_MASTER=$master_node"
+    cmd="$cmd; export GASPI_SOCKET=$j"
+    cmd="$cmd; export GASPI_TYP=$TYP"
+    cmd="$cmd; export GASPI_MFILE=$MFILE"
     if [ $SET_NUMA -eq 1 ]; then
-	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE;export GASPI_SET_NUMA_SOCKET=1; if [ -x $KPRG ]; then $PRG; else echo '$i': '$KPRG' not found;exit 1;fi 2> /dev/null &'"
-    else
-	cmd="/bin/sh -c 'export GASPI_MASTER=$master_node;export GASPI_SOCKET=$j;export GASPI_TYP=$TYP;export GASPI_MFILE=$MFILE; if [ -x $KPRG ]; then $PRG;else echo '$i': '$KPRG' not found;exit 1;fi 2> /dev/null &'"
+	cmd="$cmd; export GASPI_SET_NUMA_SOCKET=1"
     fi
+    cmd="$cmd; if [ -x $KPRG ]; then $PRG;else echo '$i': '$KPRG' not found;exit 1;fi 2> /dev/null &'"
 
     ssh $i $cmd  >> $RUN_FILE &
 
